### ISSUE TITLE
你好，我在运行您的代码的时候有些问题，想请教您一下？

### ISSUE THREAD

**Issue by BCWang93** [jeffery0628/ccks2020-task8#1]
就是我在运行您的baseline的时候，我使用的transformers库的版本是3.0.2，我运行的时候出现了以下的错误：
Trainable parameters: 102274668
248
250
252
252
248
250
252
252
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    run('./configs/base_config.json')
  File "train.py", line 88, in run
    main(config)
  File "train.py", line 66, in main
    trainer.train()
  File "/DATA2/disk1/wangbingchen/project/ccks2020-task8-pytorch/base/base_trainer.py", line 67, in train
    result = self._train_epoch(epoch)
  File "/DATA2/disk1/wangbingchen/project/ccks2020-task8-pytorch/trainer/trainer.py", line 59, in _train_epoch
    for batch_idx, batch_data in enumerate(self.train_iter):
  File "/home/wangbingchen/wangbingchen/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/wangbingchen/wangbingchen/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/wangbingchen/wangbingchen/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/DATA2/disk1/wangbingchen/project/ccks2020-task8-pytorch/data_process/military_data_process.py", line 179, in collate_fn
    text_token_ids = torch.LongTensor(np.array(text_token_ids))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.

错误的地方是对每句话进行embedding之后的长度不一样。。。请问您知道这怎么解决吗？我测试了在transformers2.11下是可以正常运行的。谢谢！

**Comment by jeffery0628** [comment]
你检查一下text_token_ids的数据类型看一下

**Comment by BCWang93** [comment]
> 你检查一下text_token_ids的数据类型看一下

你好，我发现问题的所在了。就是transformers2.0和3.0在对于文本中的'\n'这类的字符的处理方法不一样导致的，3.0版本中把这些字符全给扔掉了，2.0版本都映射为[unk]了，所以才导致最终的长度不一致。所以代码里的那个将文本的input_ids补齐的操作在3.0版本下可能需要更改一下。如下图：
![image](https://user-images.githubusercontent.com/31853251/90858725-54d63200-e3b9-11ea-9f52-02eaee7df646.png)
更改为以tokens_ids_length来判断最长的sentence然后进行对齐操作就行了，不能以原始text的长度为基础进行补齐了。或者您看下有没有更好的解决办法。谢谢！

**Comment by jeffery0628** [comment]
嗯，挺好的
